### ISSUE TITLE
Implement installer script for DRAM and maybe AMICI

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/PESTO#10]
Remove /DRAM from PESTO repository, but keep DRAM-based routines and check for (external) DRAM availability where these functions have been used so far.

**Comment by paulstapor** [comment]
So what do we do with the DRAM package now?

**Comment by JanHasenauer** [comment]
In D2D a few packages developed elsewhere are automatically downloaded then running the install script. This might be a solution.

**Comment by paulstapor** [comment]
Okay, we will (later) add a little install script, which is able to download and install DRAM and maybe also other things (it might also be an interesting option to do the same with Amici for examples... but to ask beforehand). For the publication: I suggest to leave the DRAM folder in the repo and I added a check in getParameterSamples, if DRAM should be called. If DRAM doesn't work, it throws an error suggesting to check the installation of DRAM.

**Comment by JanHasenauer** [comment]
okay, but what if DRAM but one of the other samplers? In this case the statistical analysis in the end of getParameterSample will through an error, or not?

**Comment by paulstapor** [comment]
The statistical analysis tools are not used by default in getParameterSamples. They can be called (there is an example doing so), but that's already everything. If the DRAM files are in the git repo (which is the case at the moment and which I also suggest to leave like that), those tools seems to work fine.

**Comment by FFroehlich** [comment]
please make sure that only necessary DRAM functions end up in the user path. DRAM packages a lot of stuff like hline or boxplot, which imho should not shadow original versions of these functions.

**Comment by dweindl** [comment]
I suggest checking if a function with that name is available, and if not, tell the user "This function requires ... which is part of the DRAM package to be in the matlab path. DRAM can be downloaded from ..." 

Automatic download would also be a solution, but I usually don't appreciate tools downloading extra stuff without asking me..

**Comment by dweindl** [comment]
Removed DRAM code and added download link (cfe8bfe 2d5c55f)
