### ISSUE TITLE
error in transfection example

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/PESTO#105]
Warning: Error in assigning final Hessian matrix. Original errror message: Subscripted assignment dimension mismatch. 
> In getMultiStarts (line 294)
  In mainTransfection (line 194)

**Comment by FFroehlich** [comment]
More errors later on:

In an assignment  A(:) = B, the number of elements in A and B must be the same.
Error in barrier
Error in fmincon (line 798)
    [X,FVAL,EXITFLAG,OUTPUT,LAMBDA,GRAD,HESSIAN] = barrier(funfcn,X,A,B,Aeq,Beq,l,u,confcn,options.HessFcn, ...
Error in getParProfilesByOptimization>optimizeProfileForParameterI (line 249)
                fmincon(@(theta_I) objectiveWrap([theta_I(I1);theta_next(j);theta_I(I2-1)],objective_function,options.obj_type,options.objOutNumber,I),... % negative log-posterior function
Error in getParProfilesByOptimization (line 86)
        parameters = optimizeProfileForParameterI(parameters, objective_function, i, options, fh);
Error in getParameterProfiles (line 209)
                        [parameters, fh] = getParProfilesByOptimization(parameters, objective_function, currentOptions, fh);

Error in mainTransfection (line 250)
parameters = getParameterProfiles(parameters, objectiveFunction, optionsPesto);

**Comment by paulstapor** [comment]
I'll clean that up...

**Comment by paulstapor** [comment]
fixed on master
