### ISSUE TITLE
ConversionReactionTest aborts on first run with "fatalAssertEqual failed"

### ISSUE THREAD

**Issue by rotton** [ICB-DCM/PESTO#117]
﻿Recently, I discovered PESTO and wanted to give it a try.
I cloned the repository, copied it to my Matlab folder and added it to the `pathdef.m`.
But when I run the `ConversionReactionTest.m` script, I get the following error:
```
Fatal assertion failed in ConversionReactionTest/testObjectiveFunction.
Test run aborted.

    ----------------
    Test Diagnostic:
    ----------------
    Likelihood function result is wrong.

    ---------------------
    Framework Diagnostic:
    ---------------------
    fatalAssertEqual failed.
    --> The values are not equal using "isequaln".
    --> The error was not within absolute tolerance.
    --> Failure table:
                 Actual             Expected              Error              RelativeError         AbsoluteTolerance  
            ________________    ________________    __________________    ____________________    ____________________
        
            32.2755461526847    32.2755461526847    7.105427357601e-15    2.20148942607745e-16    2.22044604925031e-16
    
    Actual Value:
      32.275546152684697
    Expected Value:
      32.275546152684690
```

The error originates at line 48:
https://github.com/ICB-DCM/PESTO/blob/master/tests/ConversionReactionTest.m#L48

Any idea on what is happening here? I'm using MATLAB Version 9.3 (R2017b) on Windows 10 if that matters.

**Comment by paulstapor** [comment]
Hi,
your running a unit test file in this case. And it seems like the unit test is slightly too severe here...
This file is there for testing if PESTO works properly, and therefore it checks if the objective function of the conversion reaction example is giving the correct value. It seems like in your case, the value for the objective function is slightly off, but that's roughly within the range of the working precision of MATLAB, so everything is fine actually. The unit test is just checking things too exactly.

The actual example file you're probably looking for is in the folder "examples". There, you'll find the actual conversion reaction example and many more.

I hope, this helped you.

Best,
Paul

**Comment by rotton** [comment]
Hi Paul, thanks for your quick reply.
If 
> everything is fine actually. The unit test is just checking things too exactly.

wouldn't it be better to just throw a warning instead of an error? Are there any settings I need to change in order to get this to work?
Anyway, I can confirm the `mainConversionReaction.m` script completes without error in about 6 minutes. Looking forward to using it for my own models.
Two more questions:
1. What isn't really clear from the documentation is if PESTO offers a MATLAB interface for CVODES. In a [comment](https://github.com/ICB-DCM/PESTO/blob/9cce0b9c0e882516c376b6e095643ef7d56aea11/%40PestoOptions/PestoOptions.m#L244) it says "to be implemented". Or do I need to install to AMICI for this?
2. My model is currently formulated as a MATLAB function (which I use for `fminsearch` and so on). Is it possible to call any of PESTOs methods directly on it, or do I need to rewrite it first to fit into PESTOs structure?

Regards.

**Comment by paulstapor** [comment]
Hi rotton,

concerning your remark:
I'm going to change the unit test in the near future. These unit tests are for developers, who want to check, if PESTO still runs as before, after having added new features or changed old ones.

To Question 1:
PESTO itself does not offer an interface to CVODES, AMICI does. You'll find it on the Github, too. PESTO is constructed in a way that it does not know anything about the underlying system (except that it is designed for deterministic objective functions), but only needs an objective function as a Matlab handle. Therefore, it is very easily interfacable with AMICI (you can see that e.g. in the jakstat signaling example).

To Question 2:
This depends a bit on which PESTO methods you want to use. I think the most reliable way is to rewrite it for PESTO and go the usual way with it: first optimization, then uncertainty analysis. That's not too complicated: you need the parameters-struct with parameter bound, number and names, you need Pesto options, and you need the objective function as a handle (like in the examples), that's it.
But you could also go for uncertainty analysis directly. In this case, you would have to set parameters.MS with the necessary fields yourself, but I would not recommend that fora first use.

Best,
Paul
