### ISSUE TITLE
error_count as option

### ISSUE THREAD

**Issue by LoosC** [ICB-DCM/PESTO#129]
In getMultiStarts the optimization is stopped if more than 20 objective function evaluations failed. For some models this might be a rather low number. Maybe set this als option such that the user can adapt this number?

**Comment by FFroehlich** [comment]
Isn't it 20 consecutive errors or did someone fiddle with that code again?

**Comment by paulstapor** [comment]
No, it's 20 consecutive errors

**Comment by LoosC** [comment]
Oh yes that might be right
