### ISSUE TITLE
tic toc issue on R2017b

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/PESTO#138]
https://github.com/ICB-DCM/PESTO/blob/51b786671b749233130576d22634a14c6aea16c3/private/performPT.m#L155

```
Error using toc
You must call TIC without an output argument before calling TOC without an input argument.
```

**Comment by BBallnus** [comment]
Fixed as part of the current pull request https://github.com/ICB-DCM/PESTO/pull/139/commits/d59b54b15a4f7e242ffc0a80bcba73a8e05d0374
