### ISSUE TITLE
getPropertyProfiles

### ISSUE THREAD

**Issue by paulstapor** [ICB-DCM/PESTO#14]
First creates many warnings, then crashes leaving the error message:

Error using figure
Invalid convenience arg handle

Error in plotPropertyProfiles (line 132)
        fh = figure(varargin{3});

Error in getPropertyProfiles (line 234)
                case 'visual', fh = plotPropertyProfiles(properties,'1D',fh,options.property_index,options.plot_options); disp(str);

Error in main (line 206)
properties = getPropertyProfiles(properties,parameters,objectiveFunction,optionsProperties);

**Comment by dweindl** [comment]
In which example does this occur?

**Comment by paulstapor** [comment]
in the conversion reaction example, if one tries to circumvent the getProperty/ParameterSamples

**Comment by paulstapor** [comment]
Problem solved
