### ISSUE TITLE
PestoOptions inherits from mixin.GetSet

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/PESTO#143]
Please change this (and other options inheritances to `PestoOptions < matlab.mixin.CustomDisplay`).

Temporary workaround: use copy() for deep copies of handle objects.

**Comment by BBallnus** [comment]
Who does already have experience regarding this topic and would fix it?

**Comment by FFroehlich** [comment]
Apparently this is already fixed in the branch https://github.com/ICB-DCM/PESTO/tree/feature_new_optimizers

**Comment by paulstapor** [comment]
gonna be merged next week
