### ISSUE TITLE
LiveScripts, Scripts and Functions

### ISSUE THREAD

**Issue by paulstapor** [ICB-DCM/PESTO#15]
I created a live script file (.mlx) for the enzymatic catalysis example. I think that these live scripts are very cool, especially for explaining, but they have some disadvantages: Debugging is more complicated (or: less possible), and I had the impression that they have an overhead for computation time, but didn't test it particularly... Moreover, the plotting interface works differently, plots are displayed after they are finished, refreshing und updating plots seems not to work. So having ONLY a live script is maybe not the best idea, since also compatibility is not ideal...

I would suggest having for each example a live script AND a function version of the main file. The function is more flexible, the live script a (very) nice add-on. But PESTO should also work without them...

**Comment by dweindl** [comment]
Not being able to update the plots is really a problem for the examples. Seems others were facing the same problem https://stackoverflow.com/questions/39231098/live-script-with-animation . So then back to regular scripts or functions, I guess. I really would have like the cleaner looks...

**Comment by paulstapor** [comment]
Since the LiveScripts are new, maybe they will be more powerful in the future... we can think of adding some of them, since they are really nice for comments. We can ask Jan, how we should proceed with that...

**Comment by paulstapor** [comment]
We may aim at liveScripts in a later version. For now we don't take the effort, since liveScripts also have some drawbacks: Plots are not updated, while a script part ist evaluated, meaning that dynamical updates for plot are not possible.
