### ISSUE TITLE
Reduce code duplication between *property* and *parameter* functions

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/PESTO#16]
E.g. there is extensive code duplication in getPropertyProfiles.m and getParameterProfiles.m, getParameterConfidenceIntervals.m and getPropertyConfidenceIntervals.m, ...

**Comment by paulstapor** [comment]
Maybe for a PestoVersion, one can think of removing this duplication. At the moment, we keep the splitting in parameters and properties.
