### ISSUE TITLE
Poor Optimization Initializations lead to error

### ISSUE THREAD

**Issue by BBallnus** [ICB-DCM/PESTO#160]
In cases where all inital Points for the MS optimization are rejected. PESTO throws an error, e.g. because "exitflag" in getMultiStarts() line 325,         

parameters.MS.exitflag(iMS) = exitflag;

is undefined.

**Comment by paulstapor** [comment]
Right, that's true and shouldn't be the case...
Anyway: tough thing to be in that situation... ;)

**Comment by paulstapor** [comment]
New pull-request is open to fix this.
Thanks for bringing it up!
