### ISSUE TITLE
options.save folder name unsupported on windows

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/PESTO#169]
Using the options.save = true to save results fails on Windows, probably because the syntax of options.foldername with colons (:) is not allowed.

**Comment by FFroehlich** [comment]
replace everything where '/...' is appended to `options.foldername` with a call to `fullfile(...)`. Paths with `:` should be supported, but might result in conflicts with paths that also contain `/`.

**Comment by FFroehlich** [comment]
also keep in mind that the save routine is currently broken (see #94)

**Comment by yannikschaelte** [comment]
no, in Windows at least the following seem forbidden: <>:"/\|?*
it would be possible to change to a formate like ``datestr(now, 'yyyy-mm-dd__hh-MM-ss')``
