### ISSUE TITLE
Do we need plotParameterProfiles.m and plotParameterSamples.m ?

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/PESTO#17]
They don't do anything but calling plotParameterUncertainty.m 

Was there a specific motivation to have these extra functions?

**Comment by paulstapor** [comment]
I'll have a look at them, too. Do they do something different than the same files for the Properties?

**Comment by dweindl** [comment]
They do roughly the same. There is much duplication but there are still some specific blocks.

**Comment by paulstapor** [comment]
Probably, this will be the same for the get...samples files... 
Maybe we can think of putting them together into one?

**Comment by paulstapor** [comment]
Stays for the application note, maybe we will change that in the future
