### ISSUE TITLE
Pom1 broken

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/PESTO#178]
Pom1 example not working any more, because uses amici.sol.xdot field (https://github.com/ICB-DCM/PESTO/blob/master/examples/Pom1p_gradient_formation/logLikelihoodPom1.m#L99).
Easiest solution: xdot has moved to amici.sol.diagnosis.xdot, but this should be also possible (nicer) via pre-equilibration now?

**Comment by JanHasenauer** [comment]
Sounds good. Would be great if you implement the solution.
