### ISSUE TITLE
paper citation

### ISSUE THREAD

**Issue by thomassligon** [ICB-DCM/PESTO#180]
Please include a citation to the PESTO paper in README.md. The citation might be the following, or perhaps some other format:
Stapor, P., Weindl, D., Ballnus, B., Hug, S., Loos, C., Fiedler, A., . . . Hasenauer, J. (2018). PESTO: Parameter EStimation TOolbox. Bioinformatics, 34(4), 705-707. doi: 10.1093/bioinformatics/btx676

**Comment by JanHasenauer** [comment]
done
