### ISSUE TITLE
Undefined function or variable 'getParameterSamples'.

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/PESTO#2]
When running the conversion reaction example runEstimation__CR

```
Undefined function or variable 'getParameterSamples'.

Error in runEstimation__CR (line 103)
parameters = getParameterSamples(parameters,logL,options_par);
```

**Comment by FFroehlich** [comment]
I think that function should actually exist. Must have been accidently deleted at some point. I will check if I can find it somewhere.

**Comment by FFroehlich** [comment]
Okay there is a getParameterSamples in the PESTO version in the CANPATHPRO folder but it contains  a lot of unpublished methods developed by Benni, so not including it here might be intentional. Better check with @JanHasenauer .

**Comment by dweindl** [comment]
@JanHasenauer  can you please add an appropriate version of the file when convenient?

**Comment by paulstapor** [comment]
Does anyone know if plotParameterUncertainty depends on getParamterSamples? I think it shouldn't necessarily, but in the CR example, it's in the sampling block (l.194f., below % Scatter plots). Can someone explain what it does exactly? The first plot seems to be exactly the profile likelihoods, the second seems to be the profile paths...

**Comment by FFroehlich** [comment]
no plotParameterUncertainty should not depend on getParamterSamples, but in the current implementation it might. plotParameterUncertainty can plot uncertainty from getMultiStarts (via hessian matrix returned from optimization), getParameterSamples and getParameterProfiles. Last time I checked, the checking whether a certain analysis was not done correctly.

**Comment by dweindl** [comment]
Added the missing file.
