### ISSUE TITLE
Independence of methods

### ISSUE THREAD

**Issue by paulstapor** [ICB-DCM/PESTO#21]
We need to make sure that getParameterSamples also works without running a multistart local optimization method beforehand. Do we want getParameterProfiles also to work without information from parameters.MS?

**Comment by FFroehlich** [comment]
getParameterProfiles will not (or very poorly) work without a previos succesful 
multistart. But you could just run getMultistarts with default settings and display a warning.

**Comment by JanHasenauer** [comment]
I would through a warning or even an error if the user did not run a multi-start optimisation before running profile likelihood calculation.
One could check if the corresponding fields in the parameter struct are empty.

**Comment by paulstapor** [comment]
Clearly, getParameterProfiles will perform very poorly without a multistart beforehand (maybe give bad results, in any case take ages), but it would be possible to write some lines of code, such that it would at least work at all. The question is, is it worth this effort? I don't think so, but maybe somebody has a different opinion.

**Comment by FFroehlich** [comment]
not maybe, most certainly. definitely not worth. either run a multistart or throw an error.

**Comment by JanHasenauer** [comment]
indeed. if the field MS is empty we should return an error. If the user does not employ getMultiStarts but another routine and stores the results to .MS, I would accept that to ensure modularity.

**Comment by paulstapor** [comment]
(Hopefully) done now. Sampling and Multistart should work now independently.
