### ISSUE TITLE
Features, which are not shown in examples so far

### ISSUE THREAD

**Issue by paulstapor** [ICB-DCM/PESTO#22]
Pesto can compute confidence intervals and, as far as I know but please correct me if I'm wrong, also profile for multimodal objective functions. Since this is a useful feature, we should implement this in one example.

Are there any other useful features, which are not covered by examples or which I might not know so far?

**Comment by FFroehlich** [comment]
To my knowledge multimodal objective functions (where profile calculation starting from multiple modes is required) are not supported for profile calculation.

The transfection example is a good starting point there as The separation between the modes can be easily tuned.

**Comment by JanHasenauer** [comment]
The profile calculation routine allows for the specification of the starting point (using the index), an automatic integration of profiles from multiple runs is currently however not supported.

**Comment by paulstapor** [comment]
Okay, I will write a little routine which does that... 
Should it be part of the publication, or rather of a later version?

**Comment by JanHasenauer** [comment]
A later version is in my opinion sufficient. in the case of multi-modal distributions, standard confidence intervals are anyhow problematic.

**Comment by paulstapor** [comment]
I added a little "example for bimodality" part in the transfection example. At least, this feature is now shown, a later version with merged profiles and confidence intervals will come at some point.
