### ISSUE TITLE
PestoOptions is a handle

### ISSUE THREAD

**Issue by paulstapor** [ICB-DCM/PESTO#27]
At a certain point, we should change that, since the following problem can appear:

options1 = PestoOptions();
...do some assignments to options1
options2 = options1;
...do some assignments to options2

The latter assignments will also change the object in options1, which is counter-intuitive and can lead to wrong results.

**Comment by FFroehlich** [comment]
in AMICI we now inherit from matlab.mixin.CustomDisplay (adapted from the SolverOptions class). I think this is a good choice for PESTO aswell.

**Comment by dweindl** [comment]
Fixed in e5bf4f7a478f2501a691f602d7ee1b877c50b07b
