### ISSUE TITLE
3 versions of collectResults.m

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/PESTO#3]
What are the different collectResults.m files? Which one should we use?

collectResults.m
collectResults.m-d1552287-482b-4c88-a3c7-e5c52d475cf7
collectResults.m-e232cfd4-c3d6-40d3-9086-3379c1d58234

**Comment by JanHasenauer** [comment]
Good question. I seems that collectResults.m is the right one and the rest can be deleted.

**Comment by dweindl** [comment]
Okay, removed the additional ones in 0f9b915472fc34b0801fe9bbf4ce08587d1bd3e7
