### ISSUE TITLE
Interface to global optimizer(s)

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/PESTO#32]
Add PSwarm interface to getMultiStarts.m:
http://www.norg.uminho.pt/aivaz/pswarm/

**Comment by dweindl** [comment]
PSwarm only running on windows due to AMPL / matampl dependency.

**Comment by dweindl** [comment]
EvA2 (http://www.ra.cs.uni-tuebingen.de/software/eva2/index.html) not working, matlab bindings missing

**Comment by JanHasenauer** [comment]
PSwarm is also running on linux and mac. Merely the examples are problematic. The call looks like this:

% Options
Options_PS.Size    = 1e1*parameters.number;
Options_PS.MaxIter = 1e4*parameters.number;
Options_PS.MaxObj  = 1e4*parameters.number;
Options_PS.IPrint = -1;

% Initial guess
x0 = bsxfun(@plus,parameters.min,bsxfun(@times,rand(parameters.number,options.n_starts),(parameters.max-parameters.min)));

% Run the algorithm
[theta,J,RunData] = PSwarm(Problem_PS,struct('x',x0(:,i)),Options_PS);

**Comment by dweindl** [comment]
Ah, thanks. :+1:

**Comment by dweindl** [comment]
In progress on branch "meigo". Providing interface to MEIGO and PSwarm.
