### ISSUE TITLE
Third argument is not of type PestoOptions when calling getMultiStarts

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/PESTO#36]
structs passed to as arguments which should be PestoOptions passed to those functions should be automatically cast into PestoOptions.

also according to camel code, it should be called pestoOptions, not PestoOptions.

**Comment by dweindl** [comment]
> also according to camel code, it should be called pestoOptions, not PestoOptions.
Class names usually start with uppercase letters. Is there a good reason to change that?

**Comment by FFroehlich** [comment]
hmm actually camel case does not specify whether the first letter is capitalised. So you are right and we should indeed actually follow class naming conventions (start with uppercase letter).

**Comment by FFroehlich** [comment]
fixed in 86d83a3
