### ISSUE TITLE
slow plotting for many multistarts

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/PESTO#41]
loops at 

https://github.com/ICB-DCM/PESTO/blob/master/plotMultiStarts.m#L100

and

https://github.com/ICB-DCM/PESTO/blob/master/plotMultiStarts.m#L154 

are super slow for large number of multistarts because i is set to length(parameters.MS.logPost) and not number of finished multistarts.

**Comment by paulstapor** [comment]
okay, on my list, thanks

**Comment by paulstapor** [comment]
fixed in the current pull request
