### ISSUE TITLE
ambiguous default pesto options for MCMC

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/PESTO#43]
when generating default pesto options the fields .MCMC.nsimu_warmup and  .MCMC.nsimu_run are empty but do indeed have default values (according to documentation)

**Comment by paulstapor** [comment]
Due to new Sampling routines, this will soon be obsolete.

**Comment by FFroehlich** [comment]
issues should only be closed when they are fixed in the **master** branch and at no point before that. If, for any reason, the commit does not end up in the master branch is and never will be fixed. This is why you use the "fixed #43" in the commit such that you do not forget to close the issue later on.

**Comment by dweindl** [comment]
@paulstapor This issue is resolved now?

**Comment by paulstapor** [comment]
currently having a look, gimme a moment
