### ISSUE TITLE
Functions lacking examples

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/PESTO#5]
The following functions do not come with examples and are not used by any other function:

* collectResults
* GelmanRubinstat
* logmvnpdf
* plotMCMCdiagnosis
* testGradient
* updateCovariance
* updateStatistics
* xticklabel_rotate (remove?)

I guess we should provide examples for all of them or remove the obsolete ones.

**Comment by FFroehlich** [comment]
GelmanRubinstat,plotMCMCdiagnosis,updateCovariance,updateStatistics,logmvnpdf is probably related to the sampling code that Benni is working on. I would add them to .gitignore.

testGradient should be integrated with other examples but an individual example is probably also good to have a unit/regression test for it.

xticklabel_rotate can be removed (I think this is supported by MATLAB now, also probably no longer functional after the hg2 update).

**Comment by dweindl** [comment]
Okay, thanks. Removed  xticklabel_rotate 4c08b0a5de50ab8eee95980d8fe2070162741c37  and moved presumably internal functions to private/ 3c27961cea8e6d952226dffc73d454d7f42eaf83.

**Comment by dweindl** [comment]
Some of them belong to getParameterSamples. The remaining used ones are removed in 3b3c25d.
