### ISSUE TITLE
overhead in getPropertySamples with 'visual'

### ISSUE THREAD

**Issue by BBallnus** [ICB-DCM/PESTO#52]
I recently realized that getPropertySamples is _very_ slow (43s for 2k sample iterations) in the conversionReaction example.

The largest portion (29s) of time goes into the 21 calls of plotPropertyUncertainty which updates the legend and histogram bars each time. Indeed, it updates every 100 MCMC iterations as coded in line 119 of getPropertySamples:

        if (mod(j,100) == 0) || (j == length(properties.S.logPost))

I suggest to change it to 10%, 20%, ... of the iterations instead or removing the sequential drawing entirely.

**Comment by dweindl** [comment]
Sounds good. Maybe add it as an option with 10% as default?

**Comment by JanHasenauer** [comment]
Agreed.

At some point one might include an adaptive strategy based on the expected computation time.

**Comment by BBallnus** [comment]
Ok, I changed the code to a percentage heuristic for now and gonna merge it into development in near future. An adaptive strategy sounds good. I'd suggest we implement it together with the modularization / expansion of the visularization tools as mentioned in issue #49
