### ISSUE TITLE
obj_w_error_count

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/PESTO#53]
the calls of obj_w_error_count (https://github.com/ICB-DCM/PESTO/blob/master/getMultiStarts.m#L615) and obj are not consisten (i think they should be).
Also the function uses eval instead of feval. Eval creates invisible temporary variables and should only be used if there really is no other way. You could do something like feval(varargin{2},varargin{1,4}) instead and also avoid the additional switch statement.

**Comment by paulstapor** [comment]
Classical won't fix on this branch, since this function is about to become obsolete anyway ;). In the develop branch, it does not exist any more, but a global wrapper function is used, which is the same for optimization, profiles and sampling. This one does not use eval any more.
