### ISSUE TITLE
Mandatory approval of pull requests?

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/PESTO#54]
Shall we make review and approval of pull requests mandatory for PESTO? I think it would be a good idea, at least for master. It will help to recognize potential issues early on, it is likely to improve code organization and quality, and more people will feel responsible and in touch with the different parts of PESTO.

**Comment by FFroehlich** [comment]
Already have it in place for MEMOIR and AMICI, I think it makes a lot of sense.

**Comment by FFroehlich** [comment]
implemented
