### ISSUE TITLE
Open Pesto-Issues for Release

### ISSUE THREAD

**Issue by paulstapor** [ICB-DCM/PESTO#62]
A list of things which I think are necessary to fix.
- [x] collectResults should work properly (@FFroehlich : can you have a look? You used it at least...)
- [ ] All examples need to be commented in the same way (also the non-Main-files) and work with the same naming scheme (variables which do the same thing in different examples should have the same name) (Paul)
- [x] There should be a global list, what functionalities are shown in the examples. In every example, the list what it demonstrates should be complete. (Paul)
- [ ] Examples should work, when little changes are done (changing the mode of output, changing to a different optimizer, yada yada...) (Paul)
- [x] Documentation must fit to the current version (haven't had a look, maybe this is already the case) (@dweindl : can you do that?)
- [x] The new sampling options should work for all examples, sampling should plot the same way it did before (=comparable to the other routines). (Benny)
- [x] Regression tests and runPestTests should cover most of the important functionality (@ dweindl : can you do this? You can also use RosenbrockTest.m in the test folder, since its small and very, very fast...)
- [x] Make Pesto also run when no PestoOptions, but a struct with the same fields (or little changes like things were in the old versions, e.g. options.fmincon instead of options.localOptimizerOptions) is provided (for backward campatibility) ---> who ever has time, maybe use old setDefault-function for a starting point
- [x] The same should hold true more or less for Sampling options (backward compatibility) in the best case, but this I see as optional, since there things have changed so much, that it may be very hard...
- [x] output.mode 'text' and 'silent' and 'visual' should do what they ought to: 'visual' opens windows, prints one line when finished, 'text' prints most important results to console, no plotting, 'silent' does nothing. This needs to be tested... ---> who ever has time
- [x] Organize the entries in the PestoOptions() in a similar way (sections, spacing) to the samplingOptions, to make it easier to find things, delete old sampling options, comment options for profile integration (Paul)

...to be continued, but these are the first which came to my mind

**Comment by dweindl** [comment]
So to summarize, except for these two coding tasks,
> - Make Pesto also run when no PestoOptions, but a struct with the same fields (or little changes like things were in the old versions, e.g. options.fmincon instead of options.localOptimizerOptions) is provided (for backward campatibility) ---> who ever has time, maybe use old setDefault-function for a starting point
> - The same should hold true more or less for Sampling options (backward compatibility) in the best case, but this I see as optional

 there is only testing to be done for now, right?

**Comment by FFroehlich** [comment]
please use `- [ ] ` to make bullet points checkable. makes tracking of what is done and what not easier and avoids excessive email spam. collectResults was fine for me.

**Comment by FFroehlich** [comment]
for the pesto options thing you can copy the following 5 lines from AMICI: 
https://github.com/ICB-DCM/AMICI/blob/master/%40amioption/amioption.m#L107

**Comment by dweindl** [comment]
> for the pesto options thing you can copy the following 5 lines from AMICI: 
https://github.com/ICB-DCM/AMICI/blob/master/%40amioption/amioption.m#L107
(this makes you have all the default options and internal checks directly available for the import)

The whole thing is already based on the amioption class. What needs to be changed is the argument check in the other functions. I will do that.

**Comment by dweindl** [comment]
Anybody feeling responsible for any of the tasks, please open a new issue (one per task) and assign yourself.

**Comment by dweindl** [comment]
Priority should be fixing these issues: https://github.com/ICB-DCM/PESTO/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Release+1.0%22+label%3Abug

The other points are rather vague and will not cause any errors. Although they are nice to have... 
I created the release-1.0 branch from develop for the first stable release. Any new features not listed above should be kept in develop for the moment.

**Comment by paulstapor** [comment]
I think we got a confusion about who is doing the last task (although I wrote in my first post I would do it, but I didn't make up an issue of its own for that):

I did some work on that, which I consider to be basically complete (only the PesoOptions.m). But I don't want to push it, before I know that I don't mess up someone else's work.
@dweindl : I pulled your last commit and as far as I see, I don't change things you did with one exception: I put an additional "%" in front of header lines, to make those things to appear more clearly in the Matlab editor. Please tell me, if this screws something up for doxygen (Or just remove the additional "%"s: it's not so many of them ;) ).

Do I have your okay to push my commit? @dweindl ? @BBallnus ?

**Comment by dweindl** [comment]
@paulstapor Doxygen stumbles over '%%' within the class body. Within a member function it is fine, but not outside. This header line will end up in the documentation for the next class member. That is why i changed them e.g. in 50672705d5643b70206fe20d9fb5b19d152d320a .
Sounds okay for me to push, but I could give a more definite answer if you create a pull request.

**Comment by paulstapor** [comment]
Okay, I will remove those "%%". Then, I have basically nothing changed but rearranged the properties, to group them in a more intuitive way (and added a description for profile integration options).

**Comment by dweindl** [comment]
@paulstapor After changing the descriptions, please recreate the documentation and check for warnings/errors in the log and shortly check the respective section in the pdf.
Note: Comments within struct definitions unfortunately break mtoc++/doxygen.

**Comment by paulstapor** [comment]
I'll take care of the examples in the next 3 or 4 days (and will also take care of the pre-last point). Then I think, the list is finished... Maybe: The pre-pre-last point, we skip, right?
Trying to ensure backward compatibility on something which has changed so much seems a bit pointless to me by now...
