### ISSUE TITLE
incorrect results in plotMultiStartDiagnosis

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/PESTO#63]
I have a parameter struct with MS.t_cpu ~10^3-10^4, but values plotted are 10^0-10^1, MS.n_iter ~ 10^2-10^3, but values plotted are 10^0-10^1, MS.n_objfun ~10^2-10^3, but values plotted are 10^0-10^1.

**Comment by paulstapor** [comment]
Seems like some offset... That was Sabrinas code, but since she's not here right now, I will give it a look...

**Comment by FFroehlich** [comment]
it's a static assignment of XTicks 🙈, will take care and also add some more plots I always wanted anyways.

**Comment by FFroehlich** [comment]
fixed in 	3b482e1
