### ISSUE TITLE
Can't check dimensions of theta0 and sigma0

### ISSUE THREAD

**Issue by BBallnus** [ICB-DCM/PESTO#69]
Another problem caused by the separation of parameters & options:

I'm currently writing a PestoSamplingClass. Problem: The dimension of parameter space is currently only stored in the parameter struct and thus not accessible within the setter methods of the sampling options where I'd like to check the dimensions. Any good ideas on how to transfer this information between both objects?

**Comment by dweindl** [comment]
Yes, that is a problem for the parameter-dependent default options. 

I did not come up with a satisfying solution yet. So far, some settings are checked in the getP*.m as for example in https://github.com/ICB-DCM/PESTO/blob/master/getMultiStarts.m#L107

One option would be to have an Options constructor taking the parameters to set default values.

**Comment by BBallnus** [comment]
I think making the check in getP* for now is a good idea indeed. Thank you!

**Comment by dweindl** [comment]
We can set all parameter-dependent options to [] per default and add a class method .setDefaults(parameters) to be called at the beginning of getParameterSamples() etc. which initializes the parameter-dependent options if still empty. This way, we would have still all default options together in the class definition.
