### ISSUE TITLE
Example enzymatic catalysis broken

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/PESTO#7]
```
 Perform optimization...Warning: Objective function has too many input arguments for the chosen optimization method. 
> In getMultiStarts (line 236)
  In main (line 82)
  In run (line 96) 
Do you want to pass additionally the whole dataset? Errors may occur... (y/n)
```
This is caused by the minibatch optimization. 

Can we simply remove the "options" from the objective function?

**Comment by paulstapor** [comment]
Which example are you testing? This should only occur if you pass an objective function with more than one input, which would usually crash Pesto anyway.
I think for a cleaned up version of Pesto, we should switch this off. In the long term, it would be good to always have an options struct as a second input (makes sense for minibatch, as well as conjugate gradient methods)

**Comment by paulstapor** [comment]
Reworked the example, corrected this.
