### ISSUE TITLE
PestoSamplingOptions and PestoOptions cleanup

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/PESTO#71]
Sampling options in PestoOptions need to be cleaned up, plenty of duplicate entries. All only sampling-relevant options should be only contained in PestoSamplingOptions. All options that are not used anymore should be removed.

The option member documentation from getParameterSamples should be moved to PestoSamplingOptions or removed completely.

@BBallnus Can you take care of that?

**Comment by BBallnus** [comment]
I'm currently working things out by shifting everything into the PestoSamplingClass

**Comment by paulstapor** [comment]
Well... I will clean up the options anyway. By tomorrow morning, this will already been done... ;)

**Comment by BBallnus** [comment]
Dont Do anything redundant please. As I mentioned, Im already workout on IT.

**Comment by paulstapor** [comment]
I'm talking about PestoOptions, not about the SamplingOptions. And I said some days ago that I will take care of that. So which options are you talking about? General options or sampling options?

**Comment by BBallnus** [comment]
The Sampling Options should be completed now.

**Comment by paulstapor** [comment]
PestoOptions should also be okay by now
