### ISSUE TITLE
Problem with PestoOptions after recent changes

### ISSUE THREAD

**Issue by BBallnus** [ICB-DCM/PESTO#72]
When running the Ring example I'm getting the following error message:

> Error using PestoOptions
> Error: File: PestoOptions.m Line: 4 Column: 10
> Cannot specify a set function for property 'property_index' in class 'PestoOptions', because that property is not defined by that class.
> 
> Error in mainExampleRing (line 27)
> optMS = PestoOptions();

**Comment by dweindl** [comment]
Hm, for me it stops with
>Reference to non-existent field 'mode'.

>Error in performPT (line 139)
      switch opt.mode

>Error in getParameterSamples (line 52)
         parameters.S = performPT( wrappedObjFkt, parameters, opt );

**Comment by dweindl** [comment]
@BBallnus did that happen with the latest commit in develop?

PestoOptions clearly has that property:
> @PestoOptions/PestoOptions.m:294:        property_index = [];

**Comment by BBallnus** [comment]
I think I found the problem... somehow 3 lines of PESTOOptions vanished due to my local merge with Pauls recent changes in develop.
