### ISSUE TITLE
examples_documentation.md

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/PESTO#75]
https://github.com/ICB-DCM/PESTO/blob/master/examples/examples_documentation.md currently does not list plotMultiStartsDiagnosis (probably none of the examples use that function)

also it states that all PESTO features are demonstrated in the Conversion reaction examples, which thereby evidently is not true (also features enabled via options.trace, options.save and options.tempsave are not demonstrated could be done via plotMultiStartsDiagnosis)

**Comment by paulstapor** [comment]
Maybe one little thing to that:
I'm currently working things out in a way, that basically all feature of PESTO are demonstrated in one of the three small examples:
 - conversion reaction
 - transfection
 - enzymatic catalysis
I think its not necessarily the best thing to demonstrate evrything in one example: This would mean ~40 figures popping up in the conversion reaction

**Comment by dweindl** [comment]
We can break it into several files. All features should preferable be demonstrated on a rather fast running example. Doesn't have to be the conversion reaction, although I think it would be a good choice.

**Comment by paulstapor** [comment]
Definitely is a good choice, transfection is also fast.
I'm currently trying to figure out what's wrong with the catalysis...

**Comment by paulstapor** [comment]
I basically took care of this, now just waiting for this getting on the master branch
