### ISSUE TITLE
PESTO option .isMinibatch redundant?

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/PESTO#8]
E.g. in getMultistart.m: 
Isn't the option .isMinibatch redundant with .optimizer?

isMinibatch = (optimizer == 'minibatch')
or not?

**Comment by FFroehlich** [comment]
Not necessarily. You can use minibatch style optimizers on the full dataset as well as on smaller batches. For the full dataset you do not need to pass a index set at every optimization. For the smaller batches you need to specify the index set online during optimization.

**Comment by paulstapor** [comment]
I removed this functionality for the application note.
