### ISSUE TITLE
Offset in plotParameterUncertainty

### ISSUE THREAD

**Issue by paulstapor** [ICB-DCM/PESTO#83]
There seems to be an offset in plotParameterUncertainty for Profiles and Approximations vs Samples...
![samples](https://cloud.githubusercontent.com/assets/11852219/24223587/33f5fd7a-0f57-11e7-9a70-080950a5d934.png)

**Comment by JanHasenauer** [comment]
Does this have to be a mistake?

**Comment by paulstapor** [comment]
There are examples when this gets worse... and it really looks like a mistake then... and afaik, it wasn't there some months ago...
At least I have this impression, that this is a mistake... (Conversion example to be seen here. Things should REALLY fit there.)
@FFroehlich : You encountered some offset in another plotting routine. How was it solved?

**Comment by JanHasenauer** [comment]
okay, if it wasn't there, this is an indication that something went wrong during updating. Apparently, in general, profiles and histograms of MCMC samples can however be shifted.

**Comment by paulstapor** [comment]
We agreed on the fact that it can really be the case: marginals are not maximum projections...
In our algorithms we trust. So we close this.
Btw.: It's really necessary to get this thing finished. We start to see bugs, which are no bugs...
